---
Name: silverstripejobsconfig
---
Dynamic\Jobs\Page\JobCollectionController:
  managed_object: Dynamic\Jobs\Page\Job
  extensions:
    - Dynamic\Collection\CollectionExtension
    - Dynamic\Jobs\Extensions\JobCollectionExtension